# Generated by Django 5.1 on 2024-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_member_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
