# Generated by Django 5.1 on 2024-08-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_member_age_member_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='age',
            new_name='Id',
        ),
    ]
