# Generated by Django 4.2.4 on 2024-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_rename_age_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
